version: 2

# Settings common to each job.
anchor_1: &defaults
  working_directory: ~/elm-run-length-encoding
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - restore_cache:
          key: dependency-cache-{{ checksum "elm-package.json" }}
      - run: npm run elm:install
      - save_cache:
          key: dependency-cache-{{ checksum "elm-package.json" }}
          paths:
            - elm-stuff
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "elm-package.json" }}
      - run: npm run elm:test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
